name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - if: runner.os == 'Linux'
      name: Setup Mono runtime
      run: |
        sudo gpg --homedir /tmp --no-default-keyring --keyring /usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/debian stable-buster main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt install dirmngr ca-certificates gnupg
        sudo apt update
        sudo apt install mono-complete

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build - Release
      run: dotnet build -c Release src/Framework.sln

    - name: Test - Debug
      run: dotnet test src/Framework.sln
