name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Assembly Version'
        required: true
  release:
    types: [published]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build and Test
      run: dotnet test -c Release src/Framework.sln

    - name: Pack
      run: dotnet pack -c Release --no-build --output . --version-suffix ${{github.run_number}} src/Cloudtoid.Framework/Cloudtoid.Framework.csproj 

    - name: Push
      run: dotnet nuget push YellowDogMan.Cloudtoid.Framework.*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
